markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

host: lxyhust.com
disqus_shortname: reedhong
title: lxyhust
subtitle: 我在这里
ga: UA-2922788-2
avatar: /images/avatar.png
custom:
    category:
        beauty: 护肤点滴
        work: 工作点滴
        product: 产品点滴
    categories:
      - name:  beauty
        title: 护肤点滴

      - name:  work
        title: 工作点滴

      - name:  product
        title: 产品点滴

meta:
    authors:
      - name: lxyhust
        email: lxyhust@gmail.com
        gravatar: 1cd8c12591616d8c22aaa624f8c07834

    gravatar:
        base: http://www.gravatar.com/avatar/
        param: ?s=
